# Generated by Django 2.2 on 2021-04-21 08:15

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='内容')),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('star_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users', verbose_name='作者')),
            ],
        ),
    ]
