# Generated by Django 2.2 on 2021-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-release_time'], 'verbose_name': '新闻信息', 'verbose_name_plural': '新闻信息'},
        ),
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(default='avatar/default.png', upload_to='news/banner', verbose_name='轮播图'),
        ),
    ]
