# Generated by Django 2.2 on 2021-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_code', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('send_type', models.IntegerField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-send_time'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('nickname', models.CharField(default='江湖骗子', max_length=30, verbose_name='昵称')),
                ('description', models.CharField(default='这个人很懒，什么都没写', max_length=200, verbose_name='简介')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(-1, '保密'), (1, '男'), (0, '女')], default=-1, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', upload_to='avatar/%Y%m%d/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (2, '认证机构'), (3, '管理员')], default=1, verbose_name='用户类型')),
                ('be_like_num', models.IntegerField(default=0, verbose_name='获赞数')),
                ('star_num', models.IntegerField(default=0, verbose_name='收藏数')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
