# Generated by Django 2.2 on 2021-04-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210424_1453'),
        ('post', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '认证机构')], default=1, verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='MyStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_type', models.IntegerField(choices=[(1, '新闻'), (2, '帖子')], verbose_name='收藏类型')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('news', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='新闻')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.Posts', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users', verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
