# Generated by Django 2.2 on 2021-04-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210424_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mystar',
            name='news',
        ),
        migrations.RemoveField(
            model_name='mystar',
            name='post',
        ),
        migrations.AddField(
            model_name='mystar',
            name='news_id',
            field=models.IntegerField(blank=True, default=1, verbose_name='新闻id'),
        ),
        migrations.AddField(
            model_name='mystar',
            name='post_id',
            field=models.IntegerField(blank=True, default=1, verbose_name='帖子id'),
        ),
    ]
